export default {
    TINT_COLOR: '#2f95dc',
    TINT_COLOR_DARKER: '#0061ba',
    APP_BACKGROUND: '#FFF',
    TAB_ICON_DEFAULT: '#ccc',
    TAB_ICON_SELECTED: '#2f95dc',
    TAB_BAR: '#fefefe',
    ERROR_BACKGROUND: 'red',
    ERROR_TEXT: '#fff',
    WARNING_BACKGROUND: '#EAEB5E',
    WARNING_TEXT: '#666804',
    NOTICE_BACKGROUND: '#2f95dc',
    NOTICE_TEXT: '#fff',
    WHITE: '#FFF',
    MODAL_BACKGROUND: '#FFF',
    PRIMARY: '#2f95dc',
    ACCENT: '#DDD',
    TEXT_PRIMARY: '#161011',
    TEXT_INVERTED: '#FFF',
    TEXT_ACCENT: '#f30016',
    FADDED_TEXT: '#939393',
    SEPARATOR: '#E2E2E2'
};
