export default interface IReduxAction {
	type: 'CLOSE_TRANSACTIONS' | 'OPEN_TRANSACTIONS' | 'OPEN_CARD_FORM' | 'CLOSE_CARD_FORM' | 'OPEN_TRANSACTIONS_FORM' | 'CLOSE_TRANSACTIONS_FORM' | 'OPEN_WALLET' | 'CLOSE_WALLET'
}
